### ISSUE TITLE
'set' doesn't trigger onSelect

### ISSUE THREAD

**Issue by mschinis** [antennaio/jquery-bar-rating#44]
onSelect is not triggered when the 'set' method is used.

Example;
`$('#photo-rating').barrating('set',4)`

**Comment by antennaio** [comment]
Thanks for reporting, the callback will be triggered when 'set' method is used.

**Comment by mschinis** [comment]
Awesome, thanks!

**Comment by amilligan** [comment]
We just came across this change in the new version.  This is the type of change that will break existing code; it deserves at least a minor version update, as well as an explanation of the change.

As an example, most client code has to deal with asynchronous data from the server, as well as user input.  We can assume the client is listening to the `onSelect` event in order to update a record when the user selects a rating.  However, if the server reports a change to the rating, after the client has rendered the old rating, the client will then update the rating view using the `set` method.  Now, with this change, the client will receive the event due to its own change, and try to update the server with the new value, which isn't new at all.

Whether programmatic changes should invoke callbacks is outside the scope of this issue (and almost certainly a question that will remain as unanswered as most holy-war-style questions).  However, this is a real problem, and one that will affect many users of your library (most, probably, without their knowledge, leading no doubt to some frustrating bugs).  If this is the approach you prefer, I would suggest a `silent` option, allowing the `set` method to set ratings without triggering the callback.

**Comment by antennaio** [comment]
Sorry to hear this latest update caused you trouble.

The change was introduced in version 1.1.2. I'd suggest to always install a specific version of the plugin and check the [changelog](https://github.com/antennaio/jquery-bar-rating/blob/master/CHANGELOG.md) when upgrading to a newer version to avoid any surprises.

I will also consider the silent option you mentioned.

**Comment by antennaio** [comment]
I added a `silent` option for those people that do not want the callbacks to be fired when the rating is controlled programmatically with methods such as `set`.

**Comment by amilligan** [comment]
Thanks for adding the silent option; could we please have a new version with this feature?

**Comment by antennaio** [comment]
Here you go:

https://github.com/antennaio/jquery-bar-rating/releases/tag/v1.1.3
