### ISSUE TITLE
Needs features

### ISSUE THREAD

**Issue by brand404** [antennaio/jquery-bar-rating#48]
Missing such basic things like ability to set to readonly AFTER a rating is selected.  Seems you can only set readonly on initializing.  huh?  Not being able to provide decimal values is odd.  Sure u can't see the results of decimals (e.g. 4.5/5) but to ignore it instead of just using a floor/ceiling on the value is like no one is even working on this project.  No need to fork, this project hasnt even begun.  Off to the next ones.  bye.

**Comment by garygreen** [comment]
The author of the plugin has always wanted to keep this as simple as possible (#8) so it does not support decimal ratings.  Technically it's an invalid value, as plugin doesn't even support half ratings but let's assume it did, it would have to decide whether to round or ceil. Some developers might have strong objections to either so best to leave it down to the developer.

I do agree it would be nice to have a way of changing an existing instance of barrating into a read-only state. Something like `$('#bars').barrating('setOption', { readonly: true });`. In any case it's pretty easy at the moment as you can just destroy and re-initialize the instance with read only option if you want.

The author has spent a long time developing this plugin and I don't think it's fair or justified in any way to give a snap review as you have done just because it's not quite to your taste. I couldn't be more happier with the plugin and thank @antennaio for any voluntary work done on it. May I suggest you look for a new plugin that handles half ratings if this is not suitable.

**Comment by antennaio** [comment]
Enough said @garygreen. Switching readonly on & off after initialization is something that I'll add soon as it will make it easier to work with the plugin.

Good luck @brand404
