### ISSUE TITLE
Is it possible to display fractional rating using "fontawesome-stars" theme?

### ISSUE THREAD

**Issue by DebeshNayak** [antennaio/jquery-bar-rating#66]

**Comment by antennaio** [comment]
Font Awesome library contains two variants of a half-star icon:

http://fontawesome.io/icon/star-half/
http://fontawesome.io/icon/star-half-o/

You could use the `star-half` icon to display fractional ratings by building a custom theme... That being said, I tried both and `star-half-o` turned out to be more suitable for this, that's why I used it to build the 'fontawesome-stars-o' theme with support for fractional ratings.

**Comment by DebeshNayak** [comment]
Thanks Kazik.

On Fri, Jun 10, 2016 at 4:58 PM, Kazik <notifications@github.com> wrote:

> Font Awesome library contains two variants of a half-star icon:
>
> http://fontawesome.io/icon/star-half/
> http://fontawesome.io/icon/star-half-o/
>
> You could use the star-half icon to display fractional ratings by
> building a custom theme... That being said, I tried both and star-half-o
> turned out to be more suitable for this, that's why I used it to build the
> 'fontawesome-stars-o' theme with support for fractional ratings.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/antennaio/jquery-bar-rating/issues/66#issuecomment-225158638>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AONgIS4ReGE2YVc_V7DG717Jgg5Cx523ks5qKUpXgaJpZM4Ix88t>
> .
>



-- 
Regards,
Debesh Nayak,
Software Development Engineer
www.DeZyre.com - Get job-ready by doing hands-on projects


Click here <http://www.dezyre.com/reviews/dezyre-hadoop-training-reviews/19> to
read reviews on DeZyre courses -
http://www.dezyre.com/reviews/dezyre-hadoop-training-reviews/19
