### ISSUE TITLE
Set with float doesnt update stars

### ISSUE THREAD

**Issue by takiesobie** [antennaio/jquery-bar-rating#76]
Hi,

When I tried to update rates with:
$('#selector').barrating('set', 1.5);
it doesnt work. It works well with INTs and initialrate though.

I wonder if you could update your code or upload unpacked code cause in dist folder there is only an min version : /

BRs,
P.

**Comment by antennaio** [comment]
The `set` method is used to set a rating based on the value of one of the options in the underlying select field. Here you can see the expected behaviour:
https://github.com/antennaio/jquery-bar-rating/blob/master/test/jquery.barrating-spec.js#L454

And here is a link to unminified plugin:
https://github.com/antennaio/jquery-bar-rating/blob/master/jquery.barrating.js

cheers!
